export const file = [
  {
    card: {
      "@type": "type.googleapis.com/swiggy.presentation.food.v2.Dish",
      info: {
        id: "127044037",
        name: "Almond Rocks (250g)",
        category: "Christmas Specials",
        description:
          "Perfectly toasted and crisp almonds coated in dark chocolate.",
        imageId:
          "FOOD_CATALOG/IMAGES/CMS/2024/12/13/c74ca2e7-b6ea-4499-bd51-35ea03c01e1b_7eb8c543-5b4b-4f10-9b4e-87701bd19414.jpg",
        inStock: 1,
        isVeg: 1,
        price: 65000,
        variants: {},
        variantsV2: {},
        itemAttribute: {
          vegClassifier: "VEG",
        },
        ribbon: {},
        showImage: true,
        itemBadge: {},
        badgesV2: {},
        ratings: {
          aggregatedRating: {
            rating: "4.8",
            ratingCount: "7 ratings",
            ratingCountV2: "7",
          },
        },
      },
      analytics: {},
      hideRestaurantDetails: true,
    },
  },
  {
    card: {
      "@type": "type.googleapis.com/swiggy.presentation.food.v2.Dish",
      info: {
        id: "127044038",
        name: "Almond Rocks (500g)",
        category: "Christmas Specials",
        description:
          "Perfectly toasted and crisp almonds coated in dark chocolate.",
        imageId:
          "FOOD_CATALOG/IMAGES/CMS/2024/12/13/ab2ed620-bc4c-4415-9c9f-8e4dd53dd8e5_353282c2-49e4-42c2-a1a2-c5f055bc1059.jpg",
        inStock: 1,
        isVeg: 1,
        price: 130000,
        variants: {},
        variantsV2: {},
        itemAttribute: {
          vegClassifier: "VEG",
        },
        ribbon: {},
        showImage: true,
        itemBadge: {},
        badgesV2: {},
        ratings: {
          aggregatedRating: {},
        },
      },
      analytics: {},
      hideRestaurantDetails: true,
    },
  },
  {
    card: {
      "@type": "type.googleapis.com/swiggy.presentation.food.v2.Dish",
      info: {
        id: "135638784",
        name: "Premium Gift Hamper Bag",
        category: "Gifting",
        description:
          "An assortment of our signature products - Eggless assorted brownies, Chocolate chip cookies (8pc), Butter palmiers (50g), Sweet Sesame crackers (100g) & Cheese crackers (100g)",
        imageId: "150f32549957a2aa3e586fd899ea4b08",
        inStock: 1,
        isVeg: 1,
        price: 79900,
        variants: {},
        variantsV2: {},
        itemAttribute: {
          vegClassifier: "VEG",
        },
        ribbon: {},
        showImage: true,
        itemBadge: {},
        badgesV2: {},
        ratings: {
          aggregatedRating: {},
        },
      },
      analytics: {},
      hideRestaurantDetails: true,
    },
  },
  {
    card: {
      "@type": "type.googleapis.com/swiggy.presentation.food.v2.Dish",
      info: {
        id: "100256939",
        name: "Indulgence Gift Hamper Basket",
        category: "Gifting",
        description:
          "An assortment of our signature products - Assorted brownies (6pc), Chocolate chip cookies (8pc), Dense loaf (350g), Butter cookies (10pc), Mava cake (300g), Almond biscotti (150g), Chocolate coated biscuits (9pc), Pound Cake (210g) & Almond rocks (250g)",
        imageId:
          "FOOD_CATALOG/IMAGES/CMS/2024/7/25/d38f1038-9013-4a07-9f9b-6a3553242280_692e4a3f-58f5-415b-b932-53174d586b11.jpg_compressed",
        inStock: 1,
        price: 320000,
        variants: {},
        variantsV2: {},
        itemAttribute: {
          vegClassifier: "NONVEG",
        },
        ribbon: {},
        showImage: true,
        itemBadge: {},
        badgesV2: {},
        ratings: {
          aggregatedRating: {},
        },
      },
      analytics: {},
      hideRestaurantDetails: true,
    },
  },
  {
    card: {
      "@type": "type.googleapis.com/swiggy.presentation.food.v2.Dish",
      info: {
        id: "132233935",
        name: "Indulgence Gift Hamper Basket (Eggless)",
        category: "Gifting",
        description:
          "An assortment of signature products- Assorted Eggless Brownies (6pc), Chocolate Chip Cookies (8pc), Eggless Dense loaf (260g), Cheese Crackers (100g), Eggless Mava Cake (225g), Orange Cookies (12pc), Chocolate coated biscuits (9pc), Butter Cookies (10pc), Almond Rocks (250g)",
        imageId:
          "FOOD_CATALOG/IMAGES/CMS/2024/7/25/d38f1038-9013-4a07-9f9b-6a3553242280_692e4a3f-58f5-415b-b932-53174d586b11.jpg_compressed",
        inStock: 1,
        isVeg: 1,
        price: 320000,
        variants: {},
        variantsV2: {},
        itemAttribute: {
          vegClassifier: "VEG",
        },
        ribbon: {},
        showImage: true,
        itemBadge: {},
        badgesV2: {},
        ratings: {
          aggregatedRating: {},
        },
      },
      analytics: {},
      hideRestaurantDetails: true,
    },
  },
  {
    card: {
      "@type": "type.googleapis.com/swiggy.presentation.food.v2.Dish",
      info: {
        id: "100256940",
        name: "Luxury Gift Hamper Basket",
        category: "Gifting",
        description:
          "An assortment of our signature products - Assorted brownies (6pc), Chocolate chip cookies (8pc), Dense loaf (350g), Butter cookies (10pc), Mava cake (300g), Black pepper sourdough crackers (100g) & Almond biscotti (150g)",
        imageId: "ae2866da7d053115a5671a81bab04613",
        inStock: 1,
        price: 230000,
        variants: {},
        variantsV2: {},
        itemAttribute: {
          vegClassifier: "NONVEG",
        },
        ribbon: {},
        showImage: true,
        itemBadge: {},
        badgesV2: {},
        ratings: {
          aggregatedRating: {},
        },
      },
      analytics: {},
      hideRestaurantDetails: true,
    },
  },
  {
    card: {
      "@type": "type.googleapis.com/swiggy.presentation.food.v2.Dish",
      info: {
        id: "100256941",
        name: "Premium Gift Hamper Basket",
        category: "Gifting",
        description:
          "An assortment of our signature products - Assorted brownies (4pc), Double choco chip cookies (8pc), Dense loaf (350g), Butter cookies (10pc), Ragi crackers (100g) & Butter palmiers (50g)",
        imageId: "6f121c775297f6266d1bf371e2d56b97",
        inStock: 1,
        price: 170000,
        variants: {},
        variantsV2: {},
        itemAttribute: {
          vegClassifier: "NONVEG",
        },
        ribbon: {},
        showImage: true,
        itemBadge: {},
        badgesV2: {},
        ratings: {
          aggregatedRating: {
            rating: "4.6",
            ratingCount: "3 ratings",
            ratingCountV2: "3",
          },
        },
      },
      analytics: {},
      hideRestaurantDetails: true,
    },
  },
  {
    card: {
      "@type": "type.googleapis.com/swiggy.presentation.food.v2.Dish",
      info: {
        id: "132233933",
        name: "Premium Gift Hamper Basket (Eggless)",
        category: "Gifting",
        description:
          "An assortment of signature products - Assorted Eggless Brownies (4pc), Chocolate Chip cookies (8pc), Eggless Dense loaf (260g), Butter Cookies (10pc), Ragi Crackers (100g), Butter Palmiers (50g)",
        imageId:
          "FOOD_CATALOG/IMAGES/CMS/2024/7/25/9b12f1bd-19a3-4047-a0f3-5674f911b5a7_41d1ead7-109b-4d19-9c3e-be3488519e84.jpg",
        inStock: 1,
        isVeg: 1,
        price: 170000,
        variants: {},
        variantsV2: {},
        itemAttribute: {
          vegClassifier: "VEG",
        },
        ribbon: {},
        showImage: true,
        itemBadge: {},
        badgesV2: {},
        ratings: {
          aggregatedRating: {},
        },
      },
      analytics: {},
      hideRestaurantDetails: true,
    },
  },
  {
    card: {
      "@type": "type.googleapis.com/swiggy.presentation.food.v2.Dish",
      info: {
        id: "133485670",
        name: "Eggless Rich Chocolate Cake [1/2kg]",
        category: "Cakes",
        description:
          "A traditional cake made by layering chocolate sponge with rich and smooth chocolate cream, and decorated with dark chocolate.",
        imageId: "f2bd0cb79c209530c0ec4a8d864ed54c",
        inStock: 1,
        isVeg: 1,
        price: 59500,
        variants: {},
        variantsV2: {},
        addons: [
          {
            groupId: "170238134",
            groupName: "Cake Toppers",
            choices: [
              {
                id: "123120993",
                name: "Congratulations",
                price: 4000,
                inStock: 1,
                isVeg: 1,
                isEnabled: 1,
              },
              {
                id: "123120994",
                name: "Thank You",
                price: 4000,
                inStock: 1,
                isVeg: 1,
                isEnabled: 1,
              },
              {
                id: "123120989",
                name: "Happy Anniversary",
                price: 4000,
                inStock: 1,
                isVeg: 1,
                isEnabled: 1,
              },
              {
                id: "123120990",
                name: "Happy Birthday",
                price: 4000,
                isVeg: 1,
                isEnabled: 1,
              },
            ],
            maxAddons: 1,
            maxFreeAddons: -1,
          },
          {
            groupId: "170238135",
            groupName: "Candles",
            choices: [
              {
                id: "123120991",
                name: "Twisted Candles (Small)",
                price: 3000,
                inStock: 1,
                isVeg: 1,
                isEnabled: 1,
              },
              {
                id: "123120995",
                name: "Magic Candles",
                price: 6000,
                inStock: 1,
                isVeg: 1,
                isEnabled: 1,
              },
              {
                id: "123120992",
                name: "Twisted Candles (Big)",
                price: 4000,
                inStock: 1,
                isVeg: 1,
                isEnabled: 1,
              },
              {
                id: "123120996",
                name: "Spiral Candles",
                price: 7500,
                inStock: 1,
                isVeg: 1,
                isEnabled: 1,
              },
            ],
            maxAddons: 1,
            maxFreeAddons: -1,
          },
        ],
        itemAttribute: {
          vegClassifier: "VEG",
        },
        ribbon: {
          text: "Bestseller",
          textColor: "#ffffff",
          topBackgroundColor: "#d53d4c",
          bottomBackgroundColor: "#b02331",
        },
        showImage: true,
        offerTags: [
          {
            title: "20% OFF",
            subTitle: "USE PARTY",
            textColor: "#DB6742",
            backgroundColor: "#FAE8E3",
            matchText: "SILD",
          },
        ],
        itemBadge: {},
        badgesV2: {},
        isBestseller: true,
        ratings: {
          aggregatedRating: {
            rating: "4.8",
            ratingCount: "34 ratings",
            ratingCountV2: "34",
          },
        },
      },
      analytics: {},
      hideRestaurantDetails: true,
    },
  },
  {
    card: {
      "@type": "type.googleapis.com/swiggy.presentation.food.v2.Dish",
      info: {
        id: "133485671",
        name: "Eggless Butterscotch & Milk Chocolate Cake [1/2kg]",
        category: "Cakes",
        description:
          "A moist butterscotch cake made with vanilla cream, house-made butterscotch sauce, crunchy butterscotch, and finished with a milk chocolate glaze.",
        imageId: "18c696fa1421cbae87fe1be2dae9ca53",
        inStock: 1,
        isVeg: 1,
        price: 56500,
        variants: {},
        variantsV2: {},
        addons: [
          {
            groupId: "170238005",
            groupName: "Cake Toppers",
            choices: [
              {
                id: "123120993",
                name: "Congratulations",
                price: 4000,
                inStock: 1,
                isVeg: 1,
                isEnabled: 1,
              },
              {
                id: "123120994",
                name: "Thank You",
                price: 4000,
                inStock: 1,
                isVeg: 1,
                isEnabled: 1,
              },
              {
                id: "123120989",
                name: "Happy Anniversary",
                price: 4000,
                inStock: 1,
                isVeg: 1,
                isEnabled: 1,
              },
              {
                id: "123120990",
                name: "Happy Birthday",
                price: 4000,
                isVeg: 1,
                isEnabled: 1,
              },
            ],
            maxAddons: 1,
            maxFreeAddons: -1,
          },
          {
            groupId: "170238006",
            groupName: "Candles",
            choices: [
              {
                id: "123120991",
                name: "Twisted Candles (Small)",
                price: 3000,
                inStock: 1,
                isVeg: 1,
                isEnabled: 1,
              },
              {
                id: "123120995",
                name: "Magic Candles",
                price: 6000,
                inStock: 1,
                isVeg: 1,
                isEnabled: 1,
              },
              {
                id: "123120992",
                name: "Twisted Candles (Big)",
                price: 4000,
                inStock: 1,
                isVeg: 1,
                isEnabled: 1,
              },
              {
                id: "123120996",
                name: "Spiral Candles",
                price: 7500,
                inStock: 1,
                isVeg: 1,
                isEnabled: 1,
              },
            ],
            maxAddons: 1,
            maxFreeAddons: -1,
          },
        ],
        itemAttribute: {
          vegClassifier: "VEG",
        },
        ribbon: {
          text: "Bestseller",
          textColor: "#ffffff",
          topBackgroundColor: "#d53d4c",
          bottomBackgroundColor: "#b02331",
        },
        showImage: true,
        offerTags: [
          {
            title: "20% OFF",
            subTitle: "USE PARTY",
            textColor: "#DB6742",
            backgroundColor: "#FAE8E3",
            matchText: "SILD",
          },
        ],
        itemBadge: {},
        badgesV2: {},
        isBestseller: true,
        ratings: {
          aggregatedRating: {
            rating: "4.5",
            ratingCount: "55 ratings",
            ratingCountV2: "55",
          },
        },
      },
      analytics: {},
      hideRestaurantDetails: true,
    },
  },
  {
    card: {
      "@type": "type.googleapis.com/swiggy.presentation.food.v2.Dish",
      info: {
        id: "127044025",
        name: "Eggless Dutch Truffle Cake [1/2kg]",
        category: "Cakes",
        description: "Dark chocolate ganache with chocolate sponge.",
        imageId: "01f50ea13d7b168d8ab2810a73e1e314",
        inStock: 1,
        isVeg: 1,
        price: 62500,
        variants: {},
        variantsV2: {},
        addons: [
          {
            groupId: "170238165",
            groupName: "Cake Toppers",
            choices: [
              {
                id: "123120993",
                name: "Congratulations",
                price: 4000,
                inStock: 1,
                isVeg: 1,
                isEnabled: 1,
              },
              {
                id: "123120994",
                name: "Thank You",
                price: 4000,
                inStock: 1,
                isVeg: 1,
                isEnabled: 1,
              },
              {
                id: "123120989",
                name: "Happy Anniversary",
                price: 4000,
                inStock: 1,
                isVeg: 1,
                isEnabled: 1,
              },
              {
                id: "123120990",
                name: "Happy Birthday",
                price: 4000,
                isVeg: 1,
                isEnabled: 1,
              },
            ],
            maxAddons: 1,
            maxFreeAddons: -1,
          },
          {
            groupId: "170238167",
            groupName: "Candles",
            choices: [
              {
                id: "123120991",
                name: "Twisted Candles (Small)",
                price: 3000,
                inStock: 1,
                isVeg: 1,
                isEnabled: 1,
              },
              {
                id: "123120995",
                name: "Magic Candles",
                price: 6000,
                inStock: 1,
                isVeg: 1,
                isEnabled: 1,
              },
              {
                id: "123120992",
                name: "Twisted Candles (Big)",
                price: 4000,
                inStock: 1,
                isVeg: 1,
                isEnabled: 1,
              },
              {
                id: "123120996",
                name: "Spiral Candles",
                price: 7500,
                inStock: 1,
                isVeg: 1,
                isEnabled: 1,
              },
            ],
            maxAddons: 1,
            maxFreeAddons: -1,
          },
        ],
        itemAttribute: {
          vegClassifier: "VEG",
        },
        ribbon: {},
        showImage: true,
        itemBadge: {},
        badgesV2: {},
        ratings: {
          aggregatedRating: {
            rating: "4.7",
            ratingCount: "96 ratings",
            ratingCountV2: "96",
          },
        },
      },
      analytics: {},
      hideRestaurantDetails: true,
    },
  },
  {
    card: {
      "@type": "type.googleapis.com/swiggy.presentation.food.v2.Dish",
      info: {
        id: "127044023",
        name: "Eggless Fresh Cream Pineapple Cake [1/2kg]",
        category: "Cakes",
        description: "Fresh cream cake with home made pineapple compote.",
        imageId: "6f46ef359dc4981ae6a0e757f1f6e434",
        inStock: 1,
        isVeg: 1,
        price: 65000,
        variants: {},
        variantsV2: {},
        addons: [
          {
            groupId: "170238140",
            groupName: "Cake Toppers",
            choices: [
              {
                id: "123120993",
                name: "Congratulations",
                price: 4000,
                inStock: 1,
                isVeg: 1,
                isEnabled: 1,
              },
              {
                id: "123120994",
                name: "Thank You",
                price: 4000,
                inStock: 1,
                isVeg: 1,
                isEnabled: 1,
              },
              {
                id: "123120989",
                name: "Happy Anniversary",
                price: 4000,
                inStock: 1,
                isVeg: 1,
                isEnabled: 1,
              },
              {
                id: "123120990",
                name: "Happy Birthday",
                price: 4000,
                isVeg: 1,
                isEnabled: 1,
              },
            ],
            maxAddons: 1,
            maxFreeAddons: -1,
          },
          {
            groupId: "170238141",
            groupName: "Candles",
            choices: [
              {
                id: "123120991",
                name: "Twisted Candles (Small)",
                price: 3000,
                inStock: 1,
                isVeg: 1,
                isEnabled: 1,
              },
              {
                id: "123120995",
                name: "Magic Candles",
                price: 6000,
                inStock: 1,
                isVeg: 1,
                isEnabled: 1,
              },
              {
                id: "123120992",
                name: "Twisted Candles (Big)",
                price: 4000,
                inStock: 1,
                isVeg: 1,
                isEnabled: 1,
              },
              {
                id: "123120996",
                name: "Spiral Candles",
                price: 7500,
                inStock: 1,
                isVeg: 1,
                isEnabled: 1,
              },
            ],
            maxAddons: 1,
            maxFreeAddons: -1,
          },
        ],
        itemAttribute: {
          vegClassifier: "VEG",
        },
        ribbon: {},
        showImage: true,
        itemBadge: {},
        badgesV2: {},
        ratings: {
          aggregatedRating: {
            rating: "4.5",
            ratingCount: "46 ratings",
            ratingCountV2: "46",
          },
        },
      },
      analytics: {},
      hideRestaurantDetails: true,
    },
  },
  {
    card: {
      "@type": "type.googleapis.com/swiggy.presentation.food.v2.Dish",
      info: {
        id: "127044028",
        name: "Chocoholic Cake [1/2kg]",
        category: "Cakes",
        description:
          "Three layers of chocolate mousse: white, milk and dark chocolate mousse layered in this crowd-favourite cake.",
        imageId: "4cfe67bfb168ed03ba5f2effaa341522",
        inStock: 1,
        isVeg: 1,
        price: 72500,
        variants: {},
        variantsV2: {},
        addons: [
          {
            groupId: "170238213",
            groupName: "Cake Toppers",
            choices: [
              {
                id: "123120993",
                name: "Congratulations",
                price: 4000,
                inStock: 1,
                isVeg: 1,
                isEnabled: 1,
              },
              {
                id: "123120994",
                name: "Thank You",
                price: 4000,
                inStock: 1,
                isVeg: 1,
                isEnabled: 1,
              },
              {
                id: "123120989",
                name: "Happy Anniversary",
                price: 4000,
                inStock: 1,
                isVeg: 1,
                isEnabled: 1,
              },
              {
                id: "123120990",
                name: "Happy Birthday",
                price: 4000,
                isVeg: 1,
                isEnabled: 1,
              },
            ],
            maxAddons: 1,
            maxFreeAddons: -1,
          },
          {
            groupId: "170238214",
            groupName: "Candles",
            choices: [
              {
                id: "123120991",
                name: "Twisted Candles (Small)",
                price: 3000,
                inStock: 1,
                isVeg: 1,
                isEnabled: 1,
              },
              {
                id: "123120995",
                name: "Magic Candles",
                price: 6000,
                inStock: 1,
                isVeg: 1,
                isEnabled: 1,
              },
              {
                id: "123120992",
                name: "Twisted Candles (Big)",
                price: 4000,
                inStock: 1,
                isVeg: 1,
                isEnabled: 1,
              },
              {
                id: "123120996",
                name: "Spiral Candles",
                price: 7500,
                inStock: 1,
                isVeg: 1,
                isEnabled: 1,
              },
            ],
            maxAddons: 1,
            maxFreeAddons: -1,
          },
        ],
        itemAttribute: {
          vegClassifier: "VEG",
        },
        ribbon: {},
        showImage: true,
        itemBadge: {},
        badgesV2: {},
        ratings: {
          aggregatedRating: {
            rating: "4.9",
            ratingCount: "38 ratings",
            ratingCountV2: "38",
          },
        },
      },
      analytics: {},
      hideRestaurantDetails: true,
    },
  },
  {
    card: {
      "@type": "type.googleapis.com/swiggy.presentation.food.v2.Dish",
      info: {
        id: "127044021",
        name: "Eggless Dutch Truffle Cake [1kg]",
        category: "Cakes",
        description: "Dark chocolate ganache with chocolate sponge.",
        imageId: "3b08c25da25361732fdc817a6045a85d",
        inStock: 1,
        isVeg: 1,
        price: 125000,
        variants: {},
        variantsV2: {},
        addons: [
          {
            groupId: "170238015",
            groupName: "Cake Toppers",
            choices: [
              {
                id: "123120993",
                name: "Congratulations",
                price: 4000,
                inStock: 1,
                isVeg: 1,
                isEnabled: 1,
              },
              {
                id: "123120994",
                name: "Thank You",
                price: 4000,
                inStock: 1,
                isVeg: 1,
                isEnabled: 1,
              },
              {
                id: "123120989",
                name: "Happy Anniversary",
                price: 4000,
                inStock: 1,
                isVeg: 1,
                isEnabled: 1,
              },
              {
                id: "123120990",
                name: "Happy Birthday",
                price: 4000,
                isVeg: 1,
                isEnabled: 1,
              },
            ],
            maxAddons: 1,
            maxFreeAddons: -1,
          },
          {
            groupId: "170238017",
            groupName: "Candles",
            choices: [
              {
                id: "123120991",
                name: "Twisted Candles (Small)",
                price: 3000,
                inStock: 1,
                isVeg: 1,
                isEnabled: 1,
              },
              {
                id: "123120995",
                name: "Magic Candles",
                price: 6000,
                inStock: 1,
                isVeg: 1,
                isEnabled: 1,
              },
              {
                id: "123120992",
                name: "Twisted Candles (Big)",
                price: 4000,
                inStock: 1,
                isVeg: 1,
                isEnabled: 1,
              },
              {
                id: "123120996",
                name: "Spiral Candles",
                price: 7500,
                inStock: 1,
                isVeg: 1,
                isEnabled: 1,
              },
            ],
            maxAddons: 1,
            maxFreeAddons: -1,
          },
        ],
        itemAttribute: {
          vegClassifier: "VEG",
        },
        ribbon: {},
        showImage: true,
        itemBadge: {},
        badgesV2: {},
        ratings: {
          aggregatedRating: {
            rating: "4.8",
            ratingCount: "18 ratings",
            ratingCountV2: "18",
          },
        },
      },
      analytics: {},
      hideRestaurantDetails: true,
    },
  },
  {
    card: {
      "@type": "type.googleapis.com/swiggy.presentation.food.v2.Dish",
      info: {
        id: "127044032",
        name: "Fresh Cream Pineapple Cake [1/2kg]",
        category: "Cakes",
        description: "Fresh cream cake with home made pineapple compote.",
        imageId: "9a16fee90eb0b4079a11a6dd2ff40a43",
        inStock: 1,
        price: 65000,
        variants: {},
        variantsV2: {},
        addons: [
          {
            groupId: "170237882",
            groupName: "Cake Toppers",
            choices: [
              {
                id: "123120993",
                name: "Congratulations",
                price: 4000,
                inStock: 1,
                isVeg: 1,
                isEnabled: 1,
              },
              {
                id: "123120994",
                name: "Thank You",
                price: 4000,
                inStock: 1,
                isVeg: 1,
                isEnabled: 1,
              },
              {
                id: "123120989",
                name: "Happy Anniversary",
                price: 4000,
                inStock: 1,
                isVeg: 1,
                isEnabled: 1,
              },
              {
                id: "123120990",
                name: "Happy Birthday",
                price: 4000,
                isVeg: 1,
                isEnabled: 1,
              },
            ],
            maxAddons: 1,
            maxFreeAddons: -1,
          },
          {
            groupId: "170237884",
            groupName: "Candles",
            choices: [
              {
                id: "123120991",
                name: "Twisted Candles (Small)",
                price: 3000,
                inStock: 1,
                isVeg: 1,
                isEnabled: 1,
              },
              {
                id: "123120995",
                name: "Magic Candles",
                price: 6000,
                inStock: 1,
                isVeg: 1,
                isEnabled: 1,
              },
              {
                id: "123120992",
                name: "Twisted Candles (Big)",
                price: 4000,
                inStock: 1,
                isVeg: 1,
                isEnabled: 1,
              },
              {
                id: "123120996",
                name: "Spiral Candles",
                price: 7500,
                inStock: 1,
                isVeg: 1,
                isEnabled: 1,
              },
            ],
            maxAddons: 1,
            maxFreeAddons: -1,
          },
        ],
        itemAttribute: {
          vegClassifier: "NONVEG",
        },
        ribbon: {},
        showImage: true,
        itemBadge: {},
        badgesV2: {},
        ratings: {
          aggregatedRating: {
            rating: "4.1",
            ratingCount: "28 ratings",
            ratingCountV2: "28",
          },
        },
      },
      analytics: {},
      hideRestaurantDetails: true,
    },
  },
  {
    card: {
      "@type": "type.googleapis.com/swiggy.presentation.food.v2.Dish",
      info: {
        id: "127044029",
        name: "Dutch Truffle Cake [1/2kg]",
        category: "Cakes",
        description: "Dark chocolate ganache with chocolate sponge.",
        imageId:
          "FOOD_CATALOG/IMAGES/CMS/2024/3/27/94c6b25c-035d-4802-849f-db85c851b442_b3b208a8-ff63-4207-be54-7a2e4cad293d.jpg",
        inStock: 1,
        price: 62500,
        variants: {},
        variantsV2: {},
        addons: [
          {
            groupId: "170237941",
            groupName: "Cake Toppers",
            choices: [
              {
                id: "123120993",
                name: "Congratulations",
                price: 4000,
                inStock: 1,
                isVeg: 1,
                isEnabled: 1,
              },
              {
                id: "123120994",
                name: "Thank You",
                price: 4000,
                inStock: 1,
                isVeg: 1,
                isEnabled: 1,
              },
              {
                id: "123120989",
                name: "Happy Anniversary",
                price: 4000,
                inStock: 1,
                isVeg: 1,
                isEnabled: 1,
              },
              {
                id: "123120990",
                name: "Happy Birthday",
                price: 4000,
                isVeg: 1,
                isEnabled: 1,
              },
            ],
            maxAddons: 1,
            maxFreeAddons: -1,
          },
          {
            groupId: "170237942",
            groupName: "Candles",
            choices: [
              {
                id: "123120991",
                name: "Twisted Candles (Small)",
                price: 3000,
                inStock: 1,
                isVeg: 1,
                isEnabled: 1,
              },
              {
                id: "123120995",
                name: "Magic Candles",
                price: 6000,
                inStock: 1,
                isVeg: 1,
                isEnabled: 1,
              },
              {
                id: "123120992",
                name: "Twisted Candles (Big)",
                price: 4000,
                inStock: 1,
                isVeg: 1,
                isEnabled: 1,
              },
              {
                id: "123120996",
                name: "Spiral Candles",
                price: 7500,
                inStock: 1,
                isVeg: 1,
                isEnabled: 1,
              },
            ],
            maxAddons: 1,
            maxFreeAddons: -1,
          },
        ],
        itemAttribute: {
          vegClassifier: "NONVEG",
        },
        ribbon: {},
        showImage: true,
        itemBadge: {},
        badgesV2: {},
        ratings: {
          aggregatedRating: {
            rating: "4.6",
            ratingCount: "70 ratings",
            ratingCountV2: "70",
          },
        },
      },
      analytics: {},
      hideRestaurantDetails: true,
    },
  },
  {
    card: {
      "@type": "type.googleapis.com/swiggy.presentation.food.v2.Dish",
      info: {
        id: "133485668",
        name: "Eggless Rich Chocolate Pastry [1 Piece]",
        category: "Pastries",
        description:
          "Chocolate sponge layered with rich and smooth chocolate cream, and decorated with dark chocolate.",
        imageId: "19292e18b114587b57a39f76c23a5007",
        inStock: 1,
        isVeg: 1,
        price: 12500,
        variants: {},
        variantsV2: {},
        addons: [
          {
            groupId: "165279660",
            groupName: "Beverages",
            choices: [
              {
                id: "121726649",
                name: "Cappuccino",
                price: 14000,
                inStock: 1,
                isVeg: 1,
                isEnabled: 1,
              },
              {
                id: "121726655",
                name: "Classic Cold Coffee [300ml]",
                price: 16100,
                inStock: 1,
                isVeg: 1,
                isEnabled: 1,
              },
              {
                id: "121726659",
                name: "Mango & Pineapple Juice (200ml)",
                price: 16100,
                inStock: 1,
                isVeg: 1,
                isEnabled: 1,
              },
              {
                id: "121726647",
                name: "Valencia Orange Juice [200ml]",
                price: 16100,
                inStock: 1,
                isVeg: 1,
                isEnabled: 1,
              },
              {
                id: "121726661",
                name: "Latte",
                price: 14000,
                inStock: 1,
                isVeg: 1,
                isEnabled: 1,
              },
              {
                id: "121726660",
                name: "Hot Chocolate",
                price: 18000,
                isVeg: 1,
                isEnabled: 1,
              },
            ],
            maxAddons: 1,
            maxFreeAddons: -1,
          },
        ],
        itemAttribute: {
          vegClassifier: "VEG",
        },
        ribbon: {
          text: "Bestseller",
          textColor: "#ffffff",
          topBackgroundColor: "#d53d4c",
          bottomBackgroundColor: "#b02331",
        },
        showImage: true,
        offerTags: [
          {
            title: "20% OFF",
            subTitle: "USE PARTY",
            textColor: "#DB6742",
            backgroundColor: "#FAE8E3",
            matchText: "SILD",
          },
        ],
        itemBadge: {},
        badgesV2: {},
        isBestseller: true,
        ratings: {
          aggregatedRating: {
            rating: "4.6",
            ratingCount: "37 ratings",
            ratingCountV2: "37",
          },
        },
      },
      analytics: {},
      hideRestaurantDetails: true,
    },
  },
  {
    card: {
      "@type": "type.googleapis.com/swiggy.presentation.food.v2.Dish",
      info: {
        id: "133485669",
        name: "Eggless Butterscotch & Milk Chocolate Pastry [1 Piece]",
        category: "Pastries",
        description:
          "Moist  butterscotch pastry made with vanilla cream, homemade butterscotch sauce, crunchy butterscotch and glaze with milk chocolate galze.",
        imageId: "7190a40e52501f5b5de9b66c5e2488a8",
        inStock: 1,
        isVeg: 1,
        price: 12000,
        variants: {},
        variantsV2: {},
        addons: [
          {
            groupId: "167842234",
            groupName: "Beverages",
            choices: [
              {
                id: "121726649",
                name: "Cappuccino",
                price: 14000,
                inStock: 1,
                isVeg: 1,
                isEnabled: 1,
              },
              {
                id: "121726655",
                name: "Classic Cold Coffee [300ml]",
                price: 16100,
                inStock: 1,
                isVeg: 1,
                isEnabled: 1,
              },
              {
                id: "121726659",
                name: "Mango & Pineapple Juice (200ml)",
                price: 16100,
                inStock: 1,
                isVeg: 1,
                isEnabled: 1,
              },
              {
                id: "121726647",
                name: "Valencia Orange Juice [200ml]",
                price: 16100,
                inStock: 1,
                isVeg: 1,
                isEnabled: 1,
              },
              {
                id: "121726661",
                name: "Latte",
                price: 14000,
                inStock: 1,
                isVeg: 1,
                isEnabled: 1,
              },
              {
                id: "121726660",
                name: "Hot Chocolate",
                price: 18000,
                isVeg: 1,
                isEnabled: 1,
              },
            ],
            maxAddons: 1,
            maxFreeAddons: -1,
          },
        ],
        itemAttribute: {
          vegClassifier: "VEG",
        },
        ribbon: {
          text: "Bestseller",
          textColor: "#ffffff",
          topBackgroundColor: "#d53d4c",
          bottomBackgroundColor: "#b02331",
        },
        showImage: true,
        offerTags: [
          {
            title: "20% OFF",
            subTitle: "USE PARTY",
            textColor: "#DB6742",
            backgroundColor: "#FAE8E3",
            matchText: "SILD",
          },
        ],
        itemBadge: {},
        badgesV2: {},
        isBestseller: true,
        ratings: {
          aggregatedRating: {
            rating: "4.3",
            ratingCount: "33 ratings",
            ratingCountV2: "33",
          },
        },
      },
      analytics: {},
      hideRestaurantDetails: true,
    },
  },
  {
    card: {
      "@type": "type.googleapis.com/swiggy.presentation.food.v2.Dish",
      info: {
        id: "127044055",
        name: "Eggless Dutch Truffle Pastry [1 Piece]",
        category: "Pastries",
        description: "Dark chocolate ganache with chocolate sponge.",
        imageId: "0872a3ab7f5d4d94e16ee81b9fee8b2f",
        inStock: 1,
        isVeg: 1,
        price: 13000,
        variants: {},
        variantsV2: {},
        addons: [
          {
            groupId: "163187738",
            groupName: "Beverages",
            choices: [
              {
                id: "121726649",
                name: "Cappuccino",
                price: 14000,
                inStock: 1,
                isVeg: 1,
                isEnabled: 1,
              },
              {
                id: "121726655",
                name: "Classic Cold Coffee [300ml]",
                price: 16100,
                inStock: 1,
                isVeg: 1,
                isEnabled: 1,
              },
              {
                id: "121726659",
                name: "Mango & Pineapple Juice (200ml)",
                price: 16100,
                inStock: 1,
                isVeg: 1,
                isEnabled: 1,
              },
              {
                id: "121726647",
                name: "Valencia Orange Juice [200ml]",
                price: 16100,
                inStock: 1,
                isVeg: 1,
                isEnabled: 1,
              },
              {
                id: "121726661",
                name: "Latte",
                price: 14000,
                inStock: 1,
                isVeg: 1,
                isEnabled: 1,
              },
              {
                id: "121726660",
                name: "Hot Chocolate",
                price: 18000,
                isVeg: 1,
                isEnabled: 1,
              },
            ],
            maxAddons: 1,
            maxFreeAddons: -1,
          },
        ],
        itemAttribute: {
          vegClassifier: "VEG",
        },
        ribbon: {
          text: "Bestseller",
          textColor: "#ffffff",
          topBackgroundColor: "#d53d4c",
          bottomBackgroundColor: "#b02331",
        },
        showImage: true,
        itemBadge: {},
        badgesV2: {},
        isBestseller: true,
        ratings: {
          aggregatedRating: {
            rating: "4.6",
            ratingCount: "118 ratings",
            ratingCountV2: "118",
          },
        },
      },
      analytics: {},
      hideRestaurantDetails: true,
    },
  },
  {
    card: {
      "@type": "type.googleapis.com/swiggy.presentation.food.v2.Dish",
      info: {
        id: "127044065",
        name: "Chocoholic Pastry [1 Piece]",
        category: "Pastries",
        description:
          "Three layers of chocolate mousse: white, milk and dark chocolate mousse.",
        imageId: "54147efdb93924058d305ec8a85137fe",
        inStock: 1,
        isVeg: 1,
        price: 15000,
        variants: {},
        variantsV2: {},
        addons: [
          {
            groupId: "163187798",
            groupName: "Beverages",
            choices: [
              {
                id: "121726649",
                name: "Cappuccino",
                price: 14000,
                inStock: 1,
                isVeg: 1,
                isEnabled: 1,
              },
              {
                id: "121726655",
                name: "Classic Cold Coffee [300ml]",
                price: 16100,
                inStock: 1,
                isVeg: 1,
                isEnabled: 1,
              },
              {
                id: "121726659",
                name: "Mango & Pineapple Juice (200ml)",
                price: 16100,
                inStock: 1,
                isVeg: 1,
                isEnabled: 1,
              },
              {
                id: "121726647",
                name: "Valencia Orange Juice [200ml]",
                price: 16100,
                inStock: 1,
                isVeg: 1,
                isEnabled: 1,
              },
              {
                id: "121726661",
                name: "Latte",
                price: 14000,
                inStock: 1,
                isVeg: 1,
                isEnabled: 1,
              },
              {
                id: "121726660",
                name: "Hot Chocolate",
                price: 18000,
                isVeg: 1,
                isEnabled: 1,
              },
            ],
            maxAddons: 1,
            maxFreeAddons: -1,
          },
        ],
        itemAttribute: {
          vegClassifier: "VEG",
        },
        ribbon: {
          text: "Bestseller",
          textColor: "#ffffff",
          topBackgroundColor: "#d53d4c",
          bottomBackgroundColor: "#b02331",
        },
        showImage: true,
        itemBadge: {},
        badgesV2: {},
        isBestseller: true,
        ratings: {
          aggregatedRating: {
            rating: "4.6",
            ratingCount: "119 ratings",
            ratingCountV2: "119",
          },
        },
      },
      analytics: {},
      hideRestaurantDetails: true,
    },
  },
];
